name: CI for Angular
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: NodeSetup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install
        run: npmci
      - name: runtests
        run: npm run test --no-watch --code-coverage --browsers=ChromeHeadlessCI